# example values
spring:
  datasource:
    url:
      jdbc:mysql://localhost:3306/search_engine
    username: root
    password: testtest
  jpa:
    hibernate.ddl-auto: create
    generate-ddl: true
    show-sql: false

indexing-settings:
  sites:
    - url: https://www.lenta.ru
      name: Лента.ру
    - url: https://www.skillbox.ru
      name: Skillbox
    - url: https://www.playback.ru
      name: PlayBack.Ru
